### ISSUE TITLE
improve ProcStatus collector to match more than just substring

### ISSUE THREAD

**Issue by baris** [Yelp/fullerite#36]
@EvanKrall wrote:

Might be nice to support more than just substring matching; I think inspiration could be taken from pgrep: regex matching, plus options to match full command line versus executable name, as well as options for exact matching.

```
       -f, --full
              The  pattern  is  normally only matched against the process
              name.  When -f is set, the full command line is used....
       -x, --exact
              Only match processes whose names (or command line if -f  is
              specified) exactly match the pattern.
```

**Comment by ericchu94** [comment]
For search string, I think we can interpret the string as regex always.

For matching options, it looks like ProcStatus doesn't follow any of these conventions currently. It matches against the first part of the command line (ie: `argv[0]`). The reason was so that we didn't need to read `/proc/<pid>/stat` for all processes, but instead only read `/proc/<pid>/cmdline`

I propose we add a flag to choose between matching either command line or process name, and ignore the `--exact` flag, since that can be done with `^myprocess$`

**Comment by ericchu94** [comment]
Also, I we can choose to match against the entire command line, and the current behavior can be achieved using a regex as follows: `^[\s]*myprcoess`

**Comment by ericchu94** [comment]
I small issue that might arise is the handling of quotations, such that the provided `^[^\s]*myprcoess` is not going to be the same as the original behavior if there are spaces inside quotes, etc

**Comment by ericchu94** [comment]
Worst case is that more processes will be matched. I don't think this issue is a stopper

**Comment by smallredbean** [comment]
I agree that we should open the option to users to match on either the command line (/proc/[pid]/cmdline) or the command name (/proc/[pid]/comm); in usual cases, command name is the filename of the executable (e.g., python, apache) while command line is the entire line you type to run the process.

As to cmdline, we should match the entire line instead of only the first part. We may resolve this by join the strings.

As to matching method, regex can support exact match too.
